### ISSUE TITLE
Utilizar las clases hijas de Ingrediente

### ISSUE THREAD

**Issue by mateohernandezs** [ninojairo/MasterChef#1]
https://github.com/ninojairo/MasterChef/blob/00831c13dc4bf8fb4651313de44d8bf54567243e/src/com/bancodebogota/fdm/MasterChef/MasterChef.java#L51

Sugerencia: Utilizar las clases hijas de Ingrediente a la hora de crearlos.

**Comment by ninojairo** [comment]
Done
