### ISSUE TITLE
Uso de this

### ISSUE THREAD

**Issue by mateohernandezs** [ninojairo/MasterChef#2]
https://github.com/ninojairo/MasterChef/blob/00831c13dc4bf8fb4651313de44d8bf54567243e/src/com/bancodebogota/fdm/MasterChef/MasterChef.java#L54

Sugerencia: Utilizar "this" para referirse a las variables de instancia que se estan utilizando en los metodos de la clase.

**Comment by ninojairo** [comment]
Done.
