### ISSUE TITLE
Clase no utilizada

### ISSUE THREAD

**Issue by mateohernandezs** [ninojairo/MasterChef#5]
https://github.com/ninojairo/MasterChef/blob/00831c13dc4bf8fb4651313de44d8bf54567243e/src/com/bancodebogota/fdm/MasterChef/Carne.java#L12

Sugerencia: Esta clase no se utilizo, el ingrediente carne se utilizo como instancia en MasterChef. Se aconsejaría eliminarla.

**Comment by ninojairo** [comment]
Done, class Carne was eliminated
